Contacts Updated
Codeshows/codeshows.github.io pull request #15
Opened 2019-04-12 10:12 UTC by Surya1231

Contacts And UI Updated

2019-04-12 10:31 UTC, rishabhKalakoti commented
You need to resolve conflicts first

2019-04-12 10:32 UTC, rishabhKalakoti requested changes

2019-04-12 10:32 UTC, rishabhKalakoti commented on index.html
> +            </li>
Just keep the icons for facebook and telegram in a line. Not the text

2019-04-12 12:37 UTC, Surya1231 commented
How to resolve this conflicts??

2019-04-12 12:40 UTC, Surya1231 commented
The resolve conflicts button in disabled? what is conflict ? and how to resolve it??

2019-04-12 15:48 UTC, rishabhKalakoti commented
Conflicts arise when you don't have the updated copy of the repository and your updates clash with another that was made in the meantime.
They can be resolved in two ways:
1. Github GUI:
Make a PR from main repo (codeshows/codeshows.gitub.io) to your fork (<your_user_name>/codeshows.github.io) and merge it (using the GitHub GUI).
The conflicting files will be opened for editing containing both the copies of the updated sections. They have to be done manually. (some tools can also be used but have to be installed).
2.  Command Line:
run,
`git add remote upstream https://github.com/codeshows/codeshows.github.io`
`git fetch upstream`
`git rebase upstream/master`
The conflicting files have to be opened manually and the final code chosen.

References:
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

2019-04-12 15:49 UTC, rishabhKalakoti commented
Conflicts arise when you don't have the updated copy of the repository and your updates clash with another that was made in the meantime.
They can be resolved in two ways:
1. Github GUI:
Make a PR from main repo (codeshows/codeshows.gitub.io) to your fork (<your_user_name>/codeshows.github.io) and merge it (using the GitHub GUI).
The conflicting files will be opened for editing containing both the copies of the updated sections. They have to be done manually. (some tools can also be used but have to be installed).
2.  Command Line:
run,
`git add remote upstream https://github.com/codeshows/codeshows.github.io`
`git fetch upstream`
`git rebase upstream/master`
The conflicting files have to be opened manually and the final code chosen.

References:
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

2019-04-13 06:01 UTC, Surya1231 commented
conflicts resolved now please merge

2019-04-13 06:20 UTC, closed without merging